# Generated by Django 2.2.4 on 2019-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advertisement', '0002_advertisement_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementTarget',
            new_name='AdvertisementsInterests',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='interests',
            field=models.ManyToManyField(through='advertisement.AdvertisementsInterests', to='user.InterestsType'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='watch_history',
            field=models.ManyToManyField(through='advertisement.WatchHistory', to='user.User'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='thumbnail',
            field=models.URLField(max_length=2500, null=True),
        ),
        migrations.AlterModelTable(
            name='advertisementsinterests',
            table='ad_interests',
        ),
    ]
