# Generated by Django 2.2.4 on 2019-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advertisement', '0003_auto_20190922_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchHistory',
            new_name='QuizHistory',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='watch_history',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='quiz_history',
            field=models.ManyToManyField(through='advertisement.QuizHistory', to='user.User'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='budget',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price_per_view',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterModelTable(
            name='quizhistory',
            table='quiz_history',
        ),
    ]
