# Generated by Django 2.2.4 on 2019-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20190923_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='quiz_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
