# Generated by Django 2.2.4 on 2019-09-26 22:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'industry_types',
            },
        ),
        migrations.CreateModel(
            name='InterestsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'interests_types',
            },
        ),
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'social_auths',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('user_name', models.CharField(max_length=254, null=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('cellphone', models.CharField(max_length=20, null=True)),
                ('thumbnail', models.URLField(max_length=2500, null=True)),
                ('account_owner', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Bank')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Gender')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UsersInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.InterestsType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'users_interests',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(through='user.UsersInterests', to='user.InterestsType'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.State'),
        ),
        migrations.CreateModel(
            name='SocialAuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_login_id', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=500, null=True)),
                ('social_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SocialAuth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
            options={
                'db_table': 'social_auth_users',
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('business_license_number', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=2500, null=True)),
                ('homepage', models.URLField(max_length=2500, null=True)),
                ('thumbnail', models.URLField(max_length=2500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('industry_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.IndustryType')),
            ],
            options={
                'db_table': 'advertisers',
            },
        ),
    ]
